### ISSUE TITLE
enhacement: pick random image

### ISSUE THREAD

**Issue by SzymonScholz** [swaywm/swaybg#11]
I know there are workarounds for achieve this result (getting random image from a list), but it can be easily included in this project without much code.

-r -> pick a random wallpaper from list of files

**Comment by emersion** [comment]
I'd rather not add this feature: it can easily be scripted.

**Comment by hhirtz** [comment]
Hey @SzymonScholz , I wrote a simple C program for this exact purpose. It has support for feh (master branch) and swaybg (separate branch).

Here's a link: <https://github.com/hhirtz/randomfeh/tree/swaybg>

**Comment by fosskers** [comment]
>  it can easily be scripted.

Similarly, for those for whom that is not easily scripted, I just patched [setwall](https://github.com/fosskers/rs-setwall) to support Sway.
