### ISSUE TITLE
Feature Request: Grab random file when pointed at a directory

### ISSUE THREAD

**Issue by oniGino** [swaywm/swaybg#15]
If I point swaybg at a directory it would be nice if it just grabbed a random file every time. 
Also even better if it refreshed on a timed interval

example: new wallpaper every 30 minutes

Here is a workaround I have in my sway config
```
exec swaybg -i $(find ~/.local/share/wallpapers/ -type f | shuf -n1)
```

doesn't help with the rotating on timed interval though...

**Comment by emersion** [comment]
Sorry, swaybg is more or less considered feature complete. Please feel free to contribute to a third-party background program or to create a new one.
