### ISSUE TITLE
Background change - flicker

### ISSUE THREAD

**Issue by fraunos** [swaywm/swaybg#17]
Hii, I just set up a live webcam image for my background with the help of https://stackoverflow.com/questions/50311320/systemd-and-sway-socket-not-detected
And my question is - is there a way to make background change more smooth? I mean not in like smooth transition, but just without the sudden flicker. Here's vid below.

![bez tytułu](https://user-images.githubusercontent.com/6673521/92614542-7772b100-f2bc-11ea-8aa3-f67f8730d015.GIF)

**Comment by oliverpool** [comment]
I just read this, which could help you: https://sylvaindurand.org/dynamic-wallpapers-with-sway/

- save the pid of the old sway-bg
- launch a new `sway-bg` with the new image
- kill the old sway-bg

```sh
    PID=`pidof swaybg`
    swaybg -i ./img/whatever.png -m fill &
    sleep 1
    kill $PID
```

**Comment by emersion** [comment]
This is due to the lack of IPC in swaybg. Introducing an IPC (e.g. similar to swaybar's) would help. Not 100% sure we want to go down this road.

**Comment by emersion** [comment]
[oguri](https://github.com/vilhalmer/oguri) now has an IPC and can change the background on-the-fly without flickering.

**Comment by emersion** [comment]
Closing as out-of-scope.
