### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by btdmaster** [swaywm/swaybg#22]
I would like to have `output` support WebP images. My personal use case is having wallpapers stored in a format that is reasonably cross-compatible as well as keeping good compression on both complicated and simple images; having half in PNG and half in JPEG seemed impractical. (An unexpected gain from this change was that the images compressed in half, from 3MB to 1.5MB!)

I have only tested this on 1.5.1 since 1.6 is still in the staging repositories in Arch and hence is at a significant risk of breaking the system.

**Comment by emersion** [comment]
Moved to swaybg, assuming this is about `output bg`.

@r-c-f is correct, we rely on gdk-pixbuf for loading images. Closing since this is an upstream issue.
