### ISSUE TITLE
Background image not read from included config

### ISSUE THREAD

**Issue by stelzch** [swaywm/swaybg#25]
## Background
I am trying to setup a shared config file for two different computers, each should have a different background image. The dotfiles are in a shared git repository, thus I include the appropriate file with the `include` statement, passing the `$HOST` environment variable.

## The Problem
swaybg does not seem to respect included config files. If I run `sway -c sway_config` (which includes my_config), the background image is not shown, if I run `sway -c my_config` it is shown.

my_config:
```
output LVDS-1 bg "$HOME/Pictures/Wallpaper/landscape-4114839_1920.jpg" fill
```

sway_config:
```
include "my_config.txt"
```

## Log
When I run swaybg manually, it outputs:
```
2021-05-25 16:11:38 - [swaybg-1.0/main.c:295] Could not find config for output LVDS-1 (Unknown 0x03DF 0x00000000)
```

**Comment by emersion** [comment]
Your bug report is missing Sway debug logs. Please add a link to the full debug log file.

**Comment by stelzch** [comment]
[See here](https://gist.github.com/stelzch/b15d226c98ad056c175f20bbb578106b).

The most relevant lines seem to be:
```
00:00:00.124 [sway/config.c:404] Loading config from tmp/sway_config
00:00:00.124 [sway/config.c:818] Read line 1: include "my_config_$HOST"
00:00:00.124 [sway/commands.c:377] Config command: include "my_config_$HOST"
00:00:00.124 [sway/commands.c:397] After replacement: include "my_config_$HOST"
```

**Comment by emersion** [comment]
This is about Sway's configuration. Please open a Sway pull request if you think it's worth it to mention that paths are relative to the current working directory.

**Comment by stelzch** [comment]
Alright, thank you :+1:
