### ISSUE TITLE
Any way to determine current wallpaper?

### ISSUE THREAD

**Issue by quaintdev** [swaywm/swaybg#31]
Hello

I was trying to develop a GUI utility to set Sway wallpapers. The major hurdle at the moment is I could not find a reliable way to determine the current wallpaper. 

I was hoping if a command line parameter ```-current``` with swaybg could provide the list of wallpapers set per monitor. 

Thanks

**Comment by emersion** [comment]
Sorry, this isn't in-scope for swaybg.
