### ISSUE TITLE
High CPU usage with Wayfire

### ISSUE THREAD

**Issue by demostanis** [swaywm/swaybg#33]
![image](https://user-images.githubusercontent.com/40673815/138945748-5253e3ec-8936-4065-998a-5926ab18e671.png)
![image](https://user-images.githubusercontent.com/40673815/138945826-cb58f65e-91c4-4ca4-9bb6-fb3e13b559be.png)
Sometimes swaybg takes up to 100% of my CPU.
It wasn't doing this with Wayfire 0.7.2.
How may I debug this further?

**Comment by mfxbe** [comment]
This issue is fixed in in the master branch of wayfire.
