### ISSUE TITLE
swaybg command doesn't work until killed

### ISSUE THREAD

**Issue by I60R** [swaywm/swaybg#37]
Any attempt to launch it results in `[swaybg-1.1/main.c:321] Found config * for output LVDS-1 (Unknown 0x219D 0x00000000)`.

Maybe a message that only one `swaybg` instance is allowed would be better?

**Comment by emersion** [comment]
Multiple instances of swaybg are allowed.

**Comment by I60R** [comment]
I'm trying to call `swaybg -c '#ffffff'` and it didn't take effect, then this is displayed

**Comment by nik6ena** [comment]
Not working for me either, even upon `SIGINT`. Here is the terminal output,

```
[nik@viki ~]$ swaybg -c '#000000'
2022-03-05 03:36:05 - [swaybg-1.1/main.c:321] Found config * for output HDMI-A-2 (Dell Inc. DELL S2216H VJRF7585087T)
2022-03-05 03:36:05 - [swaybg-1.1/main.c:321] Found config * for output HDMI-A-1 (Goldstar Company Ltd LG TV 0x00000101)
^C
```

And why it don't return the prompt? I will try to understand the code later.

**Comment by HqNw** [comment]
> Multiple instances of swaybg are allowed. This message is not an error.
maybe add a flag so when its ran agian it gets killed by it self or update the command

**Comment by HqNw** [comment]
try `swaymsg output "*" bg`

**Comment by emersion** [comment]
The ordering between multiple swaybg insteances is undefined.
