### ISSUE TITLE
`swaybg` CPU spikes once a notification is shown

### ISSUE THREAD

**Issue by mizzunet** [swaywm/swaybg#41]
It seems when any notification displayed (tried `mako` and `fnott`), `swaybg` CPU spikes like 100%. 

This was first found when changing brightness and volumes changed by key binding, for which I had set to display notifications.

Here's log https://0x0.st/oZih.txt

**Comment by emersion** [comment]
Should be fixed by https://github.com/swaywm/swaybg/commit/5e2df3a600e07b71923c28a8cd51861289319c91 already. Please re-open if you can repro on master.

**Comment by mizzunet** [comment]
Cool, I installed it from master. As you said, it's been fixed. Thank you (:
