### ISSUE TITLE
Cursor does not match set cursor theme

### ISSUE THREAD

**Issue by xi-pinmping** [swaywm/swaybg#52]
Hi, I have set the cursor theme through environment, the gnome settings files, lxappearance, etc. to no avail. I have gotten every application to match the desired theme except for swaybg. I have even tried explicitly setting the XCURSOR_THEME variable when launching swaybg.

**Comment by emersion** [comment]
swaybg doesn't set any cursor. (You can configure the cursor in Sway.)

**Comment by xi-pinmping** [comment]
I have configured the cursor in sway. I have tried every way I have seen discussed to set the cursor theme and it works on everything except the background projected by swaybg. I can see the cursor I chose fine on my browser or on my bars but not on the background.
