### ISSUE TITLE
Some pictures flipped 180 only with swaybg

### ISSUE THREAD

**Issue by rieje** [swaywm/swaybg#65]
I have some pictures which when set as wallpaper with swaybg is shown upside down, yet it is shown right side up in both my image gallery app and file manager. Even when I rotate the image by 180 and save it so that it's now upside down in both the gallery app and file manager, swaybg still shows it upside down.

swaybg displays the image correctly when I use imagemagick's `-auto-orient` on the file

`jhead foo.jpg` shows the difference between the original and the `-auto-orient`ed file: the former has addditional metadata: `Orientation  : rotate 180`.

swaybg seems to not support this image orientation metadata so cannot display the image "correctly".

**Comment by emersion** [comment]
Probably need to use something like [`gdk_pixbuf_apply_embedded_orientation`](https://docs.gtk.org/gdk-pixbuf/method.Pixbuf.apply_embedded_orientation.html).

**Comment by emersion** [comment]
Done in https://github.com/swaywm/swaybg/pull/68

**Comment by rieje** [comment]
Works great, can you bump the version since it's been a while?

**Comment by emersion** [comment]
Yeah, just released a new version.
