### ISSUE TITLE
[Feature request] Animated wallpaper support

### ISSUE THREAD

**Issue by hecto600** [swaywm/swaybg#78]
Allowing short clips like with .gif or .mp4 extensions to be set as background.

**Comment by mstoeckl** [comment]
This has been requested before, but is out of scope for swaybg. Some of the programs listed under https://github.com/swaywm/sway/wiki/Useful-add-ons-for-sway#wallpaper can draw animated wallpapers; of these, `mpvpaper` is optimized for video.
